version: "3.7"
services:
# web:
# build: .
# ports:
# - "8000:80"
# depends_on:
# - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  web:
    build:
#      target: publish
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: NetRestApi
        
        
        
        
        
        
